/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDFTEMP
#define ROOMYPDFTEMP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPdftemp : public RooAbsReal {
public:
  RooMyPdftemp() {} ;
  RooMyPdftemp(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a,
	      RooAbsReal& _b);
  RooMyPdftemp(const RooMyPdftemp& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPdftemp(*this,newname); }
  inline virtual ~RooMyPdftemp() { }

protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPdftemp,1) // Your description goes here...
};
 
#endif
