/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdftemp.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdftemp);

 RooMyPdftemp::RooMyPdftemp(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _a,
                        RooAbsReal& _b) :
   RooAbsReal(name,title),
   x("x","x",this,_x),
   a("a","a",this,_a),
   b("b","b",this,_b)
 { 
 } 


 RooMyPdftemp::RooMyPdftemp(const RooMyPdftemp& other, const char* name) :
   RooAbsReal(other,name), 
   x("x",this,other.x),
   a("a",this,other.a),
   b("b",this,other.b)
 { 
 } 



 Double_t RooMyPdftemp::evaluate() const
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return (a*TMath::Sin(x/180.*TMath::Pi())/(1+b*TMath::Cos(x/180.*TMath::Pi()))) ; 
 } 



